-- ============================================
-- ÉTAPE 2 : SCRIPT SQL COMPLET POUR SUPABASE
-- Exécute ce script dans SQL Editor de Supabase
-- ============================================

-- ============================================
-- SUPPRESSION DES TABLES EXISTANTES (optionnel)
-- ============================================
-- DROP TABLE IF EXISTS support_tickets CASCADE;
-- DROP TABLE IF EXISTS announcements CASCADE;
-- DROP TABLE IF EXISTS admin_users CASCADE;
-- DROP TABLE IF EXISTS subscription_packs CASCADE;
-- DROP TABLE IF EXISTS payments CASCADE;
-- DROP TABLE IF EXISTS audit_logs CASCADE;
-- DROP TABLE IF EXISTS purchases CASCADE;
-- DROP TABLE IF EXISTS attendance CASCADE;
-- DROP TABLE IF EXISTS suppliers CASCADE;
-- DROP TABLE IF EXISTS company_info CASCADE;
-- DROP TABLE IF EXISTS settings CASCADE;
-- DROP TABLE IF EXISTS debts CASCADE;
-- DROP TABLE IF EXISTS expenses CASCADE;
-- DROP TABLE IF EXISTS losses CASCADE;
-- DROP TABLE IF EXISTS stock_movements CASCADE;
-- DROP TABLE IF EXISTS servers CASCADE;
-- DROP TABLE IF EXISTS sales CASCADE;
-- DROP TABLE IF EXISTS items CASCADE;

-- ============================================
-- TABLES APPLICATION BAR (UTILISATEUR)
-- ============================================

-- 1. TABLE DES ARTICLES
CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    name TEXT NOT NULL DEFAULT '',
    price INTEGER NOT NULL DEFAULT 0,
    purchase_price INTEGER NOT NULL DEFAULT 0,
    type TEXT NOT NULL DEFAULT 'local' CHECK (type IN ('local', 'importe')),
    depot_stock INTEGER NOT NULL DEFAULT 0,
    comptoir_stock INTEGER NOT NULL DEFAULT 0,
    sold INTEGER NOT NULL DEFAULT 0,
    barcode TEXT NOT NULL DEFAULT '',
    expiry_date TEXT DEFAULT NULL,
    photo TEXT DEFAULT NULL,
    hidden BOOLEAN NOT NULL DEFAULT false,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_items_user_id ON items(user_id);

-- 2. TABLE DES VENTES
CREATE TABLE IF NOT EXISTS sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    sale_data JSONB NOT NULL DEFAULT '{}',
    sale_date TEXT NOT NULL DEFAULT '',
    grand_total INTEGER NOT NULL DEFAULT 0,
    server_name TEXT NOT NULL DEFAULT '',
    payment_method TEXT NOT NULL DEFAULT 'cash',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_sales_user_id ON sales(user_id);

-- 3. TABLE DES SERVEURS
CREATE TABLE IF NOT EXISTS servers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    name TEXT NOT NULL DEFAULT '',
    position TEXT NOT NULL DEFAULT 'Serveur',
    start_date TEXT NOT NULL DEFAULT '',
    fixed_salary INTEGER NOT NULL DEFAULT 0,
    daily_salary INTEGER NOT NULL DEFAULT 0,
    hourly_salary INTEGER NOT NULL DEFAULT 0,
    matricule TEXT NOT NULL DEFAULT '',
    photo TEXT DEFAULT NULL,
    present BOOLEAN NOT NULL DEFAULT false,
    present_days INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_servers_user_id ON servers(user_id);

-- 4. TABLE DES MOUVEMENTS DE STOCK
CREATE TABLE IF NOT EXISTS stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    movement_type TEXT NOT NULL DEFAULT '',
    item_name TEXT NOT NULL DEFAULT '',
    qty INTEGER NOT NULL DEFAULT 0,
    value INTEGER NOT NULL DEFAULT 0,
    from_location TEXT NOT NULL DEFAULT '',
    to_location TEXT NOT NULL DEFAULT '',
    reason TEXT NOT NULL DEFAULT '',
    server_name TEXT NOT NULL DEFAULT '',
    movement_date TEXT NOT NULL DEFAULT '',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_stock_movements_user_id ON stock_movements(user_id);

-- 5. TABLE DES PERTES
CREATE TABLE IF NOT EXISTS losses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    location TEXT NOT NULL DEFAULT '',
    item_name TEXT NOT NULL DEFAULT '',
    qty INTEGER NOT NULL DEFAULT 0,
    value INTEGER NOT NULL DEFAULT 0,
    reason TEXT NOT NULL DEFAULT '',
    loss_date TEXT NOT NULL DEFAULT '',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_losses_user_id ON losses(user_id);

-- 6. TABLE DES DÉPENSES
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    amount INTEGER NOT NULL DEFAULT 0,
    expense_date TEXT NOT NULL DEFAULT '',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_expenses_user_id ON expenses(user_id);

-- 7. TABLE DES DETTES
CREATE TABLE IF NOT EXISTS debts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    debt_type TEXT NOT NULL DEFAULT 'debt' CHECK (debt_type IN ('debt', 'guarantee', 'keep')),
    item_name TEXT NOT NULL DEFAULT '',
    qty INTEGER NOT NULL DEFAULT 0,
    client_name TEXT NOT NULL DEFAULT '',
    client_phone TEXT NOT NULL DEFAULT '',
    reason TEXT NOT NULL DEFAULT '',
    value INTEGER NOT NULL DEFAULT 0,
    refund_amount INTEGER NOT NULL DEFAULT 0,
    due_date TEXT DEFAULT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid')),
    server_name TEXT NOT NULL DEFAULT '',
    debt_date TEXT NOT NULL DEFAULT '',
    paid_date TEXT DEFAULT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_debts_user_id ON debts(user_id);

-- 8. TABLE DES PARAMÈTRES (settings + trackingData + facePhotos + activityLogs + teamMembers + userPack + theme)
CREATE TABLE IF NOT EXISTS settings (
    user_id TEXT PRIMARY KEY,
    settings_data JSONB NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 9. TABLE DES INFOS ENTREPRISE
CREATE TABLE IF NOT EXISTS company_info (
    user_id TEXT PRIMARY KEY,
    company_data JSONB NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 10. TABLE DES FOURNISSEURS
CREATE TABLE IF NOT EXISTS suppliers (
    user_id TEXT PRIMARY KEY,
    suppliers_data JSONB NOT NULL DEFAULT '[]',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 11. TABLE DES POINTAGES
CREATE TABLE IF NOT EXISTS attendance (
    user_id TEXT PRIMARY KEY,
    attendance_data JSONB NOT NULL DEFAULT '[]',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 12. TABLE DES ACHATS
CREATE TABLE IF NOT EXISTS purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    purchase_data JSONB NOT NULL DEFAULT '{}',
    total INTEGER NOT NULL DEFAULT 0,
    supplier_name TEXT NOT NULL DEFAULT '',
    invoice TEXT NOT NULL DEFAULT '',
    purchase_date TEXT NOT NULL DEFAULT '',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_purchases_user_id ON purchases(user_id);

-- ============================================
-- TABLES COCKPIT ADMINISTRATIF
-- ============================================

-- 13. TABLE DES ADMINISTRATEURS
CREATE TABLE IF NOT EXISTS admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL DEFAULT '',
    email TEXT NOT NULL DEFAULT '',
    role TEXT NOT NULL DEFAULT 'support' CHECK (role IN ('super_admin', 'admin', 'support', 'compta', 'viewer')),
    is_active BOOLEAN NOT NULL DEFAULT true,
    last_login TIMESTAMPTZ DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 14. TABLE DES CLIENTS (BARS ABONNÉS)
CREATE TABLE IF NOT EXISTS clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bar_name TEXT NOT NULL DEFAULT '',
    owner_name TEXT NOT NULL DEFAULT '',
    email TEXT NOT NULL DEFAULT '',
    phone TEXT NOT NULL DEFAULT '',
    address TEXT NOT NULL DEFAULT '',
    pack_id BIGINT DEFAULT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'blocked', 'trial')),
    subscription_start DATE DEFAULT NULL,
    subscription_end DATE DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 15. TABLE DES PACKS D'ABONNEMENT
CREATE TABLE IF NOT EXISTS subscription_packs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL DEFAULT '',
    price INTEGER NOT NULL DEFAULT 0,
    duration_months INTEGER NOT NULL DEFAULT 1,
    features TEXT NOT NULL DEFAULT '',
    max_users INTEGER NOT NULL DEFAULT 1,
    max_articles INTEGER NOT NULL DEFAULT 50,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 16. TABLE DES PAIEMENTS
CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    client_name TEXT NOT NULL DEFAULT '',
    pack_id BIGINT DEFAULT NULL,
    pack_name TEXT NOT NULL DEFAULT '',
    amount INTEGER NOT NULL DEFAULT 0,
    method TEXT NOT NULL DEFAULT 'mobile_money' CHECK (method IN ('mobile_money', 'orange_money', 'airtel_money', 'visa', 'mastercard', 'cash', 'bank_transfer')),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'failed', 'refunded')),
    transaction_ref TEXT DEFAULT NULL,
    payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_payments_client_id ON payments(client_id);

-- 17. TABLE DES ANNONCES
CREATE TABLE IF NOT EXISTS announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL DEFAULT '',
    message TEXT NOT NULL DEFAULT '',
    target TEXT NOT NULL DEFAULT 'all' CHECK (target IN ('all', 'active', 'inactive', 'specific', 'trial')),
    client_id TEXT DEFAULT NULL,
    client_name TEXT DEFAULT NULL,
    start_date DATE NOT NULL DEFAULT CURRENT_DATE,
    end_date DATE NOT NULL DEFAULT CURRENT_DATE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_by TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 18. TABLE DES TICKETS SUPPORT
CREATE TABLE IF NOT EXISTS support_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    subject TEXT NOT NULL DEFAULT '',
    message TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
    priority TEXT NOT NULL DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
    assigned_to TEXT DEFAULT NULL,
    resolution TEXT DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at TIMESTAMPTZ DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS idx_tickets_user_id ON support_tickets(user_id);
CREATE INDEX IF NOT EXISTS idx_tickets_status ON support_tickets(status);

-- 19. TABLE DES LOGS D'AUDIT
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_email TEXT NOT NULL DEFAULT '',
    action TEXT NOT NULL DEFAULT '',
    details TEXT NOT NULL DEFAULT '',
    ip_address TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_audit_logs_admin ON audit_logs(admin_email);

-- ============================================
-- ACTIVATION ROW LEVEL SECURITY (RLS)
-- ============================================
ALTER TABLE items ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE servers ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE losses ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE debts ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE company_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchases ENABLE ROW LEVEL SECURITY;

ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscription_packs ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- ============================================
-- POLITIQUES RLS - APPLICATION BAR
-- ============================================
-- Permet à l'utilisateur connecté ET au compte équipe de voir/modifier les données
CREATE POLICY "Users can manage items" ON items FOR ALL USING (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%') WITH CHECK (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%');
CREATE POLICY "Users can manage sales" ON sales FOR ALL USING (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%') WITH CHECK (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%');
CREATE POLICY "Users can manage servers" ON servers FOR ALL USING (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%') WITH CHECK (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%');
CREATE POLICY "Users can manage stock_movements" ON stock_movements FOR ALL USING (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%') WITH CHECK (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%');
CREATE POLICY "Users can manage losses" ON losses FOR ALL USING (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%') WITH CHECK (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%');
CREATE POLICY "Users can manage expenses" ON expenses FOR ALL USING (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%') WITH CHECK (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%');
CREATE POLICY "Users can manage debts" ON debts FOR ALL USING (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%') WITH CHECK (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%');
CREATE POLICY "Users can manage settings" ON settings FOR ALL USING (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%') WITH CHECK (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%');
CREATE POLICY "Users can manage company_info" ON company_info FOR ALL USING (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%') WITH CHECK (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%');
CREATE POLICY "Users can manage suppliers" ON suppliers FOR ALL USING (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%') WITH CHECK (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%');
CREATE POLICY "Users can manage attendance" ON attendance FOR ALL USING (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%') WITH CHECK (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%');
CREATE POLICY "Users can manage purchases" ON purchases FOR ALL USING (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%') WITH CHECK (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%');

-- ============================================
-- POLITIQUES RLS - COCKPIT ADMIN
-- ============================================
CREATE POLICY "Admin users can view all" ON admin_users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated can view clients" ON clients FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated can view packs" ON subscription_packs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated can view payments" ON payments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated can view announcements" ON announcements FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Users can manage tickets" ON support_tickets FOR ALL USING (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%') WITH CHECK (user_id = auth.uid()::text OR user_id = 'admin-local' OR user_id LIKE '%equipe%');
CREATE POLICY "Authenticated can view audit_logs" ON audit_logs FOR ALL USING (true) WITH CHECK (true);

-- ============================================
-- ACTIVER LE TEMPS RÉEL (REALTIME)
-- ============================================
ALTER PUBLICATION supabase_realtime ADD TABLE items;
ALTER PUBLICATION supabase_realtime ADD TABLE sales;
ALTER PUBLICATION supabase_realtime ADD TABLE servers;
ALTER PUBLICATION supabase_realtime ADD TABLE stock_movements;
ALTER PUBLICATION supabase_realtime ADD TABLE losses;
ALTER PUBLICATION supabase_realtime ADD TABLE expenses;
ALTER PUBLICATION supabase_realtime ADD TABLE debts;
ALTER PUBLICATION supabase_realtime ADD TABLE settings;
ALTER PUBLICATION supabase_realtime ADD TABLE company_info;
ALTER PUBLICATION supabase_realtime ADD TABLE suppliers;
ALTER PUBLICATION supabase_realtime ADD TABLE attendance;
ALTER PUBLICATION supabase_realtime ADD TABLE purchases;
ALTER PUBLICATION supabase_realtime ADD TABLE clients;
ALTER PUBLICATION supabase_realtime ADD TABLE subscription_packs;
ALTER PUBLICATION supabase_realtime ADD TABLE payments;
ALTER PUBLICATION supabase_realtime ADD TABLE announcements;
ALTER PUBLICATION supabase_realtime ADD TABLE support_tickets;
ALTER PUBLICATION supabase_realtime ADD TABLE audit_logs;

-- ============================================
-- DONNÉES INITIALES - PACKS D'ABONNEMENT
-- ============================================
INSERT INTO subscription_packs (name, price, duration_months, features, max_users, max_articles) VALUES
    ('Free', 0, 1, 'Gestion de stock,Ventes,Serveurs,Rapports basiques', 1, 50),
    ('Starter', 5990, 1, 'Articles illimités,3 utilisateurs,Rapports avancés,Support email', 3, 999999),
    ('Pro', 12990, 1, 'Articles illimités,10 utilisateurs,Reconnaissance faciale,Support 24/7,API', 10, 999999),
    ('Entreprise', 25990, 1, 'Articles illimités,Utilisateurs illimités,API personnalisée,Formation incluse,Multi-établissements', 999999, 999999)
ON CONFLICT DO NOTHING;

-- ============================================
-- DONNÉES INITIALES - CLIENTS DÉMO
-- ============================================
INSERT INTO clients (bar_name, owner_name, email, phone, address, pack_id, status) VALUES
    ('Bar Le Relax', 'Jean Kabongo', 'lerelax@gmail.com', '+243812345678', 'Kinshasa, Gombe', 1, 'active'),
    ('Terrasse du Fleuve', 'Marie Mbala', 'terrasse.fleuve@gmail.com', '+243823456789', 'Kinshasa, Lingwala', 2, 'active'),
    ('Chez Maman Soso', 'Sophie Lukusa', 'soso@gmail.com', '+243834567890', 'Lubumbashi', 1, 'inactive'),
    ('VIP Lounge', 'Patrick Tshilombo', 'vip.lounge@gmail.com', '+243845678901', 'Goma', 3, 'active'),
    ('Bar du Coin', 'David Mbuyi', 'coin@gmail.com', '+243856789012', 'Kisangani', 1, 'blocked')
ON CONFLICT DO NOTHING;

-- ============================================
-- VÉRIFICATION FINALE
-- ============================================
SELECT 
    tablename AS table_name,
    '✅ Créée' AS status
FROM pg_catalog.pg_tables
WHERE schemaname = 'public'
  AND tablename IN (
    'items', 'sales', 'servers', 'stock_movements', 'losses', 
    'expenses', 'debts', 'settings', 'company_info', 'suppliers', 
    'attendance', 'purchases',
    'admin_users', 'clients', 'subscription_packs', 'payments',
    'announcements', 'support_tickets', 'audit_logs'
  )
ORDER BY tablename;